"""
Data models for QA Multi-Agent System
Based on: https://docs.pydantic.dev/latest/
"""
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import datetime
from enum import Enum


class TriggerType(str, Enum):
    """Trigger types for QA pipeline"""
    PUSH = "push"
    PULL_REQUEST = "pull_request"
    MANUAL = "manual"
    SCHEDULED = "scheduled"


class QualityGateStatus(str, Enum):
    """Quality gate status"""
    PENDING = "PENDING"
    PASS = "PASS"
    FAIL = "FAIL"
    WARN = "WARN"
    ERROR = "ERROR"


class AgentStatus(str, Enum):
    """Agent execution status"""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class TestStrategy(BaseModel):
    """Test strategy generated by orchestrator"""
    test_types: List[str] = Field(description="Types of tests to run")
    priority: str = Field(description="Priority level: critical, high, medium, low")
    affected_components: List[str] = Field(default_factory=list)
    estimated_duration: int = Field(description="Estimated duration in seconds")
    parallel_execution: bool = Field(default=True)
    regression_required: bool = Field(default=False)


class TestResults(BaseModel):
    """Test execution results"""
    total: int = Field(default=0, description="Total number of tests")
    passed: int = Field(default=0, description="Number of passed tests")
    failed: int = Field(default=0, description="Number of failed tests")
    skipped: int = Field(default=0, description="Number of skipped tests")
    duration: float = Field(default=0.0, description="Duration in seconds")
    failed_tests: List[Dict[str, Any]] = Field(default_factory=list)


class CoverageMetrics(BaseModel):
    """Code coverage metrics"""
    line: float = Field(default=0.0, ge=0, le=100)
    branch: float = Field(default=0.0, ge=0, le=100)
    function: float = Field(default=0.0, ge=0, le=100)
    statement: float = Field(default=0.0, ge=0, le=100)


class SecurityVulnerability(BaseModel):
    """Security vulnerability details"""
    severity: str = Field(description="critical, high, medium, low")
    title: str
    description: str
    file_path: Optional[str] = None
    line_number: Optional[int] = None
    cve_id: Optional[str] = None


class Bug(BaseModel):
    """Detected bug details"""
    severity: str = Field(description="critical, high, medium, low")
    title: str
    description: str
    file: str
    line: Optional[int] = None
    root_cause: Optional[str] = None
    suggested_fix: Optional[str] = None


class QualityGateCriteria(BaseModel):
    """Quality gate criteria"""
    min_coverage: float = Field(default=80.0, ge=0, le=100)
    max_failed_tests: int = Field(default=0, ge=0)
    max_critical_vulnerabilities: int = Field(default=0, ge=0)
    min_pass_rate: float = Field(default=95.0, ge=0, le=100)


class QualityGateActual(BaseModel):
    """Actual quality metrics"""
    coverage: float = Field(default=0.0)
    failed_tests: int = Field(default=0)
    critical_vulnerabilities: int = Field(default=0)
    pass_rate: float = Field(default=0.0)


class QualityGate(BaseModel):
    """Quality gate evaluation"""
    status: QualityGateStatus = Field(default=QualityGateStatus.PENDING)
    criteria: QualityGateCriteria
    actual: QualityGateActual
    passed: bool = Field(default=False)


class ExecutionState(BaseModel):
    """Complete execution state"""
    execution_id: str
    commit_sha: str
    branch: str
    pull_request_id: Optional[str] = None
    repo_url: str
    trigger_type: TriggerType
    author: Optional[str] = None

    # Strategy
    test_strategy: Optional[TestStrategy] = None

    # Test Results
    unit_test_results: Optional[TestResults] = None
    integration_test_results: Optional[TestResults] = None
    e2e_test_results: Optional[TestResults] = None
    performance_test_results: Optional[Dict[str, Any]] = None
    security_test_results: Optional[Dict[str, Any]] = None
    code_review_results: Optional[Dict[str, Any]] = None

    # Analysis
    test_analysis: Optional[Dict[str, Any]] = None
    detected_bugs: List[Bug] = Field(default_factory=list)

    # Quality Gate
    quality_gate: QualityGate

    # Metadata
    agents_executed: List[str] = Field(default_factory=list)
    mcp_servers_used: List[str] = Field(default_factory=list)
    retry_count: int = Field(default=0)
    execution_time: Optional[float] = None
    report_url: Optional[str] = None
    dashboard_url: Optional[str] = None
    recommendations: List[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class TriggerPayload(BaseModel):
    """Webhook trigger payload"""
    trigger_type: TriggerType
    repo_url: str
    branch: str
    commit_sha: str
    pull_request_id: Optional[str] = None
    author: Optional[str] = None
    commits: Optional[List[Dict[str, Any]]] = None


class AgentMessage(BaseModel):
    """Message sent to agents via RabbitMQ"""
    execution_id: str
    agent_name: str
    task: str
    parameters: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AgentResponse(BaseModel):
    """Response from an agent"""
    execution_id: str
    agent_name: str
    status: AgentStatus
    results: Dict[str, Any] = Field(default_factory=dict)
    error: Optional[str] = None
    duration: Optional[float] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)
